/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nsg;

public class Neighbor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Neighbor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Neighbor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nsgannJNI.delete_Neighbor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    nsgannJNI.Neighbor_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return nsgannJNI.Neighbor_id_get(swigCPtr, this);
  }

  public void setDistance(float value) {
    nsgannJNI.Neighbor_distance_set(swigCPtr, this, value);
  }

  public float getDistance() {
    return nsgannJNI.Neighbor_distance_get(swigCPtr, this);
  }

  public void setFlag(boolean value) {
    nsgannJNI.Neighbor_flag_set(swigCPtr, this, value);
  }

  public boolean getFlag() {
    return nsgannJNI.Neighbor_flag_get(swigCPtr, this);
  }

  public Neighbor() {
    this(nsgannJNI.new_Neighbor__SWIG_0(), true);
  }

  public Neighbor(long id, float distance, boolean f) {
    this(nsgannJNI.new_Neighbor__SWIG_1(id, distance, f), true);
  }

}
