/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nsg;

public class nsgannJNI {
  public final static native long new_VectorOfNeighbor__SWIG_0();
  public final static native long new_VectorOfNeighbor__SWIG_1(long jarg1, VectorOfNeighbor jarg1_);
  public final static native long VectorOfNeighbor_capacity(long jarg1, VectorOfNeighbor jarg1_);
  public final static native void VectorOfNeighbor_reserve(long jarg1, VectorOfNeighbor jarg1_, long jarg2);
  public final static native boolean VectorOfNeighbor_isEmpty(long jarg1, VectorOfNeighbor jarg1_);
  public final static native void VectorOfNeighbor_clear(long jarg1, VectorOfNeighbor jarg1_);
  public final static native long new_VectorOfNeighbor__SWIG_2(int jarg1, long jarg2, Neighbor jarg2_);
  public final static native int VectorOfNeighbor_doSize(long jarg1, VectorOfNeighbor jarg1_);
  public final static native void VectorOfNeighbor_doAdd__SWIG_0(long jarg1, VectorOfNeighbor jarg1_, long jarg2, Neighbor jarg2_);
  public final static native void VectorOfNeighbor_doAdd__SWIG_1(long jarg1, VectorOfNeighbor jarg1_, int jarg2, long jarg3, Neighbor jarg3_);
  public final static native long VectorOfNeighbor_doRemove(long jarg1, VectorOfNeighbor jarg1_, int jarg2);
  public final static native long VectorOfNeighbor_doGet(long jarg1, VectorOfNeighbor jarg1_, int jarg2);
  public final static native long VectorOfNeighbor_doSet(long jarg1, VectorOfNeighbor jarg1_, int jarg2, long jarg3, Neighbor jarg3_);
  public final static native void VectorOfNeighbor_doRemoveRange(long jarg1, VectorOfNeighbor jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorOfNeighbor(long jarg1);
  public final static native long new_VectorOfFloat__SWIG_0();
  public final static native long new_VectorOfFloat__SWIG_1(long jarg1, VectorOfFloat jarg1_);
  public final static native long VectorOfFloat_capacity(long jarg1, VectorOfFloat jarg1_);
  public final static native void VectorOfFloat_reserve(long jarg1, VectorOfFloat jarg1_, long jarg2);
  public final static native boolean VectorOfFloat_isEmpty(long jarg1, VectorOfFloat jarg1_);
  public final static native void VectorOfFloat_clear(long jarg1, VectorOfFloat jarg1_);
  public final static native long new_VectorOfFloat__SWIG_2(int jarg1, float jarg2);
  public final static native int VectorOfFloat_doSize(long jarg1, VectorOfFloat jarg1_);
  public final static native void VectorOfFloat_doAdd__SWIG_0(long jarg1, VectorOfFloat jarg1_, float jarg2);
  public final static native void VectorOfFloat_doAdd__SWIG_1(long jarg1, VectorOfFloat jarg1_, int jarg2, float jarg3);
  public final static native float VectorOfFloat_doRemove(long jarg1, VectorOfFloat jarg1_, int jarg2);
  public final static native float VectorOfFloat_doGet(long jarg1, VectorOfFloat jarg1_, int jarg2);
  public final static native float VectorOfFloat_doSet(long jarg1, VectorOfFloat jarg1_, int jarg2, float jarg3);
  public final static native void VectorOfFloat_doRemoveRange(long jarg1, VectorOfFloat jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorOfFloat(long jarg1);
  public final static native long new_VecVecFloat__SWIG_0();
  public final static native long new_VecVecFloat__SWIG_1(long jarg1, VecVecFloat jarg1_);
  public final static native long VecVecFloat_capacity(long jarg1, VecVecFloat jarg1_);
  public final static native void VecVecFloat_reserve(long jarg1, VecVecFloat jarg1_, long jarg2);
  public final static native boolean VecVecFloat_isEmpty(long jarg1, VecVecFloat jarg1_);
  public final static native void VecVecFloat_clear(long jarg1, VecVecFloat jarg1_);
  public final static native long new_VecVecFloat__SWIG_2(int jarg1, long jarg2, VectorOfFloat jarg2_);
  public final static native int VecVecFloat_doSize(long jarg1, VecVecFloat jarg1_);
  public final static native void VecVecFloat_doAdd__SWIG_0(long jarg1, VecVecFloat jarg1_, long jarg2, VectorOfFloat jarg2_);
  public final static native void VecVecFloat_doAdd__SWIG_1(long jarg1, VecVecFloat jarg1_, int jarg2, long jarg3, VectorOfFloat jarg3_);
  public final static native long VecVecFloat_doRemove(long jarg1, VecVecFloat jarg1_, int jarg2);
  public final static native long VecVecFloat_doGet(long jarg1, VecVecFloat jarg1_, int jarg2);
  public final static native long VecVecFloat_doSet(long jarg1, VecVecFloat jarg1_, int jarg2, long jarg3, VectorOfFloat jarg3_);
  public final static native void VecVecFloat_doRemoveRange(long jarg1, VecVecFloat jarg1_, int jarg2, int jarg3);
  public final static native void delete_VecVecFloat(long jarg1);
  public final static native long new_intp();
  public final static native long copy_intp(int jarg1);
  public final static native void delete_intp(long jarg1);
  public final static native void intp_assign(long jarg1, int jarg2);
  public final static native int intp_value(long jarg1);
  public final static native long new_doublep();
  public final static native long copy_doublep(double jarg1);
  public final static native void delete_doublep(long jarg1);
  public final static native void doublep_assign(long jarg1, double jarg2);
  public final static native double doublep_value(long jarg1);

  static {
    try {
        System.loadLibrary("efanna2e_d");
        System.loadLibrary("nsgann");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native void Neighbor_id_set(long jarg1, Neighbor jarg1_, long jarg2);
  public final static native long Neighbor_id_get(long jarg1, Neighbor jarg1_);
  public final static native void Neighbor_distance_set(long jarg1, Neighbor jarg1_, float jarg2);
  public final static native float Neighbor_distance_get(long jarg1, Neighbor jarg1_);
  public final static native void Neighbor_flag_set(long jarg1, Neighbor jarg1_, boolean jarg2);
  public final static native boolean Neighbor_flag_get(long jarg1, Neighbor jarg1_);
  public final static native long new_Neighbor__SWIG_0();
  public final static native long new_Neighbor__SWIG_1(long jarg1, float jarg2, boolean jarg3);
  public final static native void delete_Neighbor(long jarg1);
  public final static native int AnnBase_get_nn_by_vec(long jarg1, AnnBase jarg1_, long jarg2, int jarg3, int jarg4, long jarg5);
  public final static native int AnnBase_save_index(long jarg1, AnnBase jarg1_, String jarg2);
  public final static native int AnnBase_precision(long jarg1, AnnBase jarg1_, long jarg2, int jarg3, long jarg4, long jarg5, long jarg6);
  public final static native void delete_AnnBase(long jarg1);
  public final static native long new_Nsg__SWIG_0();
  public final static native long new_Nsg__SWIG_1(String jarg1, String jarg2, String jarg3);
  public final static native long new_Nsg__SWIG_2(int jarg1, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9);
  public final static native void delete_Nsg(long jarg1);
  public final static native int Nsg_build__SWIG_0(long jarg1, Nsg jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6, String jarg7, long jarg8, long jarg9, long jarg10);
  public final static native int Nsg_build__SWIG_1(long jarg1, Nsg jarg1_);
  public final static native int Nsg_addAll(long jarg1, Nsg jarg1_, long jarg2, VecVecFloat jarg2_);
  public final static native int Nsg_save_index(long jarg1, Nsg jarg1_, String jarg2);
  public final static native int Nsg_get_nn_by_vec(long jarg1, Nsg jarg1_, long jarg2, int jarg3, int jarg4, long jarg5);
  public final static native int Nsg_load(long jarg1, Nsg jarg1_, String jarg2, String jarg3);
  public final static native int Nsg_close(long jarg1, Nsg jarg1_);
  public final static native int Nsg_optimizeGraph(long jarg1, Nsg jarg1_);
  public final static native int Nsg_save(long jarg1, Nsg jarg1_, String jarg2, String jarg3);
  public final static native long Nsg_search(long jarg1, Nsg jarg1_, long jarg2, VectorOfFloat jarg2_, long jarg3, long jarg4);
  public final static native long Nsg_searchWithOptGraph(long jarg1, Nsg jarg1_, long jarg2, VectorOfFloat jarg2_, long jarg3, long jarg4);
  public final static native long Nsg_data(long jarg1, Nsg jarg1_);
  public final static native long Nsg_SWIGUpcast(long jarg1);
}
