/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nsg;

public class VectorOfFloat extends java.util.AbstractList<Float> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorOfFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nsgannJNI.delete_VectorOfFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfFloat(float[] initialElements) {
    this();
    reserve(initialElements.length);

    for (float element : initialElements) {
      add(element);
    }
  }

  public VectorOfFloat(Iterable<Float> initialElements) {
    this();
    for (float element : initialElements) {
      add(element);
    }
  }

  public Float get(int index) {
    return doGet(index);
  }

  public Float set(int index, Float e) {
    return doSet(index, e);
  }

  public boolean add(Float e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Float e) {
    modCount++;
    doAdd(index, e);
  }

  public Float remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorOfFloat() {
    this(nsgannJNI.new_VectorOfFloat__SWIG_0(), true);
  }

  public VectorOfFloat(VectorOfFloat other) {
    this(nsgannJNI.new_VectorOfFloat__SWIG_1(VectorOfFloat.getCPtr(other), other), true);
  }

  public long capacity() {
    return nsgannJNI.VectorOfFloat_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nsgannJNI.VectorOfFloat_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nsgannJNI.VectorOfFloat_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nsgannJNI.VectorOfFloat_clear(swigCPtr, this);
  }

  public VectorOfFloat(int count, float value) {
    this(nsgannJNI.new_VectorOfFloat__SWIG_2(count, value), true);
  }

  private int doSize() {
    return nsgannJNI.VectorOfFloat_doSize(swigCPtr, this);
  }

  private void doAdd(float x) {
    nsgannJNI.VectorOfFloat_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, float x) {
    nsgannJNI.VectorOfFloat_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private float doRemove(int index) {
    return nsgannJNI.VectorOfFloat_doRemove(swigCPtr, this, index);
  }

  private float doGet(int index) {
    return nsgannJNI.VectorOfFloat_doGet(swigCPtr, this, index);
  }

  private float doSet(int index, float val) {
    return nsgannJNI.VectorOfFloat_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    nsgannJNI.VectorOfFloat_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
