/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nsg;

public class VecVecFloat extends java.util.AbstractList<VectorOfFloat> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecVecFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecVecFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nsgannJNI.delete_VecVecFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecVecFloat(VectorOfFloat[] initialElements) {
    this();
    reserve(initialElements.length);

    for (VectorOfFloat element : initialElements) {
      add(element);
    }
  }

  public VecVecFloat(Iterable<VectorOfFloat> initialElements) {
    this();
    for (VectorOfFloat element : initialElements) {
      add(element);
    }
  }

  public VectorOfFloat get(int index) {
    return doGet(index);
  }

  public VectorOfFloat set(int index, VectorOfFloat e) {
    return doSet(index, e);
  }

  public boolean add(VectorOfFloat e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, VectorOfFloat e) {
    modCount++;
    doAdd(index, e);
  }

  public VectorOfFloat remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecVecFloat() {
    this(nsgannJNI.new_VecVecFloat__SWIG_0(), true);
  }

  public VecVecFloat(VecVecFloat other) {
    this(nsgannJNI.new_VecVecFloat__SWIG_1(VecVecFloat.getCPtr(other), other), true);
  }

  public long capacity() {
    return nsgannJNI.VecVecFloat_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nsgannJNI.VecVecFloat_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nsgannJNI.VecVecFloat_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nsgannJNI.VecVecFloat_clear(swigCPtr, this);
  }

  public VecVecFloat(int count, VectorOfFloat value) {
    this(nsgannJNI.new_VecVecFloat__SWIG_2(count, VectorOfFloat.getCPtr(value), value), true);
  }

  private int doSize() {
    return nsgannJNI.VecVecFloat_doSize(swigCPtr, this);
  }

  private void doAdd(VectorOfFloat x) {
    nsgannJNI.VecVecFloat_doAdd__SWIG_0(swigCPtr, this, VectorOfFloat.getCPtr(x), x);
  }

  private void doAdd(int index, VectorOfFloat x) {
    nsgannJNI.VecVecFloat_doAdd__SWIG_1(swigCPtr, this, index, VectorOfFloat.getCPtr(x), x);
  }

  private VectorOfFloat doRemove(int index) {
    return new VectorOfFloat(nsgannJNI.VecVecFloat_doRemove(swigCPtr, this, index), true);
  }

  private VectorOfFloat doGet(int index) {
    return new VectorOfFloat(nsgannJNI.VecVecFloat_doGet(swigCPtr, this, index), false);
  }

  private VectorOfFloat doSet(int index, VectorOfFloat val) {
    return new VectorOfFloat(nsgannJNI.VecVecFloat_doSet(swigCPtr, this, index, VectorOfFloat.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    nsgannJNI.VecVecFloat_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
