/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nsg.test;

public class AnnResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AnnResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnnResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nsgannJNI.delete_AnnResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setScore(float value) {
    nsgannJNI.AnnResult_score_set(swigCPtr, this, value);
  }

  public float getScore() {
    return nsgannJNI.AnnResult_score_get(swigCPtr, this);
  }

  public void setOffset(long value) {
    nsgannJNI.AnnResult_offset_set(swigCPtr, this, value);
  }

  public long getOffset() {
    return nsgannJNI.AnnResult_offset_get(swigCPtr, this);
  }

  public AnnResult() {
    this(nsgannJNI.new_AnnResult(), true);
  }

}
