/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nsg.test;

public class VectorOfNeighbor extends java.util.AbstractList<Neighbor> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorOfNeighbor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfNeighbor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nsgannJNI.delete_VectorOfNeighbor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfNeighbor(Neighbor[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Neighbor element : initialElements) {
      add(element);
    }
  }

  public VectorOfNeighbor(Iterable<Neighbor> initialElements) {
    this();
    for (Neighbor element : initialElements) {
      add(element);
    }
  }

  public Neighbor get(int index) {
    return doGet(index);
  }

  public Neighbor set(int index, Neighbor e) {
    return doSet(index, e);
  }

  public boolean add(Neighbor e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Neighbor e) {
    modCount++;
    doAdd(index, e);
  }

  public Neighbor remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorOfNeighbor() {
    this(nsgannJNI.new_VectorOfNeighbor__SWIG_0(), true);
  }

  public VectorOfNeighbor(VectorOfNeighbor other) {
    this(nsgannJNI.new_VectorOfNeighbor__SWIG_1(VectorOfNeighbor.getCPtr(other), other), true);
  }

  public long capacity() {
    return nsgannJNI.VectorOfNeighbor_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nsgannJNI.VectorOfNeighbor_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nsgannJNI.VectorOfNeighbor_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nsgannJNI.VectorOfNeighbor_clear(swigCPtr, this);
  }

  public VectorOfNeighbor(int count, Neighbor value) {
    this(nsgannJNI.new_VectorOfNeighbor__SWIG_2(count, Neighbor.getCPtr(value), value), true);
  }

  private int doSize() {
    return nsgannJNI.VectorOfNeighbor_doSize(swigCPtr, this);
  }

  private void doAdd(Neighbor x) {
    nsgannJNI.VectorOfNeighbor_doAdd__SWIG_0(swigCPtr, this, Neighbor.getCPtr(x), x);
  }

  private void doAdd(int index, Neighbor x) {
    nsgannJNI.VectorOfNeighbor_doAdd__SWIG_1(swigCPtr, this, index, Neighbor.getCPtr(x), x);
  }

  private Neighbor doRemove(int index) {
    return new Neighbor(nsgannJNI.VectorOfNeighbor_doRemove(swigCPtr, this, index), true);
  }

  private Neighbor doGet(int index) {
    return new Neighbor(nsgannJNI.VectorOfNeighbor_doGet(swigCPtr, this, index), false);
  }

  private Neighbor doSet(int index, Neighbor val) {
    return new Neighbor(nsgannJNI.VectorOfNeighbor_doSet(swigCPtr, this, index, Neighbor.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    nsgannJNI.VectorOfNeighbor_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
